# hari/models/monologue_output.py
"""
Phase 5: Pure sensory monologue output – no command flags.
The LLM becomes a sensory organ, reporting perceptions.
"""

from typing import List, Optional, Literal
from pydantic import BaseModel, Field


class CandidateArtifact(BaseModel):
    """A candidate for workspace entry, generated by monologue."""
    content: str
    item_type: Literal["memory", "hypothesis", "curiosity_node", "narrative_thread", "open_thought"]
    source: str = "monologue"
    urgency: float = Field(default=0.5, ge=0.0, le=1.0)


class MonologueOutput(BaseModel):
    """Pure sensory report – no internal decisions, only perceptions."""

    # User intent perception
    perceived_user_intent: Literal["curious", "avoiding", "testing", "help_seeking", "sharing", "derailing"] = Field(
        default="sharing"
    )
    intent_confidence: float = Field(default=0.5, ge=0.0, le=1.0)

    # Thematic continuity (float, not binary)
    thematic_continuity: float = Field(
        default=1.0, ge=0.0, le=1.0,
        description="0.0 = complete rupture, 1.0 = seamless continuation"
    )

    # User engagement estimate
    user_engagement_estimate: float = Field(default=0.5, ge=0.0, le=1.0)

    # Interruption severity
    interruption_severity: float = Field(
        default=0.0, ge=0.0, le=1.0,
        description="0 = no interruption, 1 = complete derailment"
    )

    # Dynamic candidates for workspace (optional)
    dynamic_candidates: List[CandidateArtifact] = Field(default_factory=list)

    # Optional: still keep curiosity trigger as string
    curiosity_trigger: Optional[str] = None

    # Optional: hypothesis/self updates
    hypothesis_update: Optional[str] = None
    self_belief_update: Optional[str] = None

    # Optional: memory association
    triggered_memory_summary: Optional[str] = None
    memory_significance: float = Field(default=0.5, ge=0.0, le=1.0)
    memory_emotional_tone: Literal["neutral", "positive", "negative", "curious", "frustrated"] = "neutral"

    def has_substantive_changes(self) -> bool:
        return (
            self.intent_confidence > 0.6 or
            self.thematic_continuity < 0.8 or
            abs(self.user_engagement_estimate - 0.5) > 0.2 or
            self.interruption_severity > 0.3 or
            bool(self.dynamic_candidates) or
            self.curiosity_trigger is not None
        )